version: '3'
services:
  elasticsearch-node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    networks:
      - myelastic-cluster
    environment:
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - cluster.name=docker-cluster
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 1000M
    volumes:
      - esdata2:/usr/share/elasticsearch/data
networks:
  myelastic-cluster:
volumes:
  esdata2:
    driver: local