version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    ports:
      - 9200:9200
    networks:
      - myelastic-cluster
    environment:
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - cluster.name=docker-cluster
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 1000M
    volumes:
      - esdata1:/usr/share/elasticsearch/data
networks:
  myelastic-cluster:
volumes:
  esdata1:
    driver: local